### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by milosmns** [robertjli/android-contacts-edit-text#3]
Are you going to publish this to jCenter/mavenCentral? If not, I will probably create a fork of it (with attribution ofc). Also, is this supporting new OS versions (i.e. permissions with API 23)?

**Comment by robertjli** [comment]
I would consider this project unmaintained, so feel free to fork, update, and publish to Maven repository. I hope my work is helpful to you!

**Comment by milosmns** [comment]
Okay, tnx.
